# Generated by Django 5.2.7 on 2026-06-23 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gestion_acces', '0001_initial'),
        ('parametrage', '0007_alter_champsdocument_type_champ'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modules', models.JSONField(blank=True, default=list, help_text='Codes des modules accessibles (ex: gestion_documentaire)')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ged_profile', to='auth.group')),
                ('localites', models.ManyToManyField(blank=True, help_text='Localités du dernier niveau attribuées au groupe', related_name='groupes_acces', to='parametrage.plangeographique')),
            ],
        ),
    ]
