# Generated by Django 5.2.15 on 2026-06-26 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_acces', '0006_entreprise_contact_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'profil utilisateur', 'verbose_name_plural': 'profils utilisateur'},
        ),
    ]
