# Generated by Django 5.2.7 on 2026-06-29 17:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_acces', '0007_alter_userprofile_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LienTelechargement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('document_ids', models.JSONField(default=list)),
                ('validity_hours', models.PositiveSmallIntegerField(choices=[(3, '3 heures'), (5, '5 heures'), (12, '12 heures'), (24, '24 heures')])),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liens_telechargement_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lien de téléchargement',
                'verbose_name_plural': 'Liens de téléchargement',
                'ordering': ['-created_at'],
            },
        ),
    ]
