# Generated by Django 5.2.7 on 2026-07-15 09:45

import config.file_validation
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_acces', '0009_groupprofile_types_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='entreprise/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), config.file_validation.UploadedFileValidator(kind='image', label='logo')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='profile_photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif']), config.file_validation.UploadedFileValidator(kind='image', label='photo')]),
        ),
    ]
