# Generated by Django 5.2.15 on 2026-07-16 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_acces', '0012_usersignature'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_utilisateur', models.CharField(blank=True, default='', help_text='Identifiant conservé même si le compte est supprimé.', max_length=150)),
                ('action', models.CharField(choices=[('connexion', 'Connexion'), ('deconnexion', 'Déconnexion'), ('connexion_echouee', 'Connexion échouée'), ('creation', 'Création'), ('modification', 'Modification'), ('suppression', 'Suppression'), ('autre', 'Autre')], db_index=True, max_length=32)),
                ('categorie', models.CharField(choices=[('authentification', 'Authentification'), ('utilisateurs', 'Utilisateurs'), ('groupes', 'Groupes'), ('documents', 'Documents'), ('parametrage', 'Paramétrage'), ('liens', 'Liens de téléchargement'), ('entreprise', 'Entreprise'), ('autre', 'Autre')], db_index=True, default='autre', max_length=32)),
                ('description', models.CharField(max_length=500)),
                ('objet_type', models.CharField(blank=True, default='', max_length=100)),
                ('objet_id', models.CharField(blank=True, default='', max_length=64)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('methode_http', models.CharField(blank=True, default='', max_length=10)),
                ('chemin', models.CharField(blank=True, default='', max_length=512)),
                ('date_creation', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_activites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "journal d'activité",
                'verbose_name_plural': "journaux d'activité",
                'ordering': ['-date_creation'],
            },
        ),
    ]
