# Generated by Django 5.2.15 on 2026-07-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_acces', '0013_journal_activite'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_backend', models.CharField(default='django.core.mail.backends.smtp.EmailBackend', help_text='Backend Django (SMTP ou console).', max_length=200)),
                ('email_host', models.CharField(default='smtp.gmail.com', max_length=255)),
                ('email_port', models.PositiveIntegerField(default=587)),
                ('email_use_tls', models.BooleanField(default=True)),
                ('email_use_ssl', models.BooleanField(default=False)),
                ('email_host_user', models.EmailField(blank=True, default='', max_length=254)),
                ('email_host_password', models.CharField(blank=True, default='', max_length=255)),
                ('default_from_email', models.CharField(blank=True, default='', help_text='Ex. GED <adresse@gmail.com>', max_length=255)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'configuration e-mail',
                'verbose_name_plural': 'configurations e-mail',
            },
        ),
        migrations.AlterField(
            model_name='journalactivite',
            name='action',
            field=models.CharField(choices=[('connexion', 'Connexion'), ('deconnexion', 'Déconnexion'), ('connexion_echouee', 'Connexion échouée'), ('creation', 'Création'), ('modification', 'Modification'), ('suppression', 'Suppression'), ('soumettre_qc', 'Soumettre QC'), ('valider_qc', 'Valider QC'), ('rejeter_qc', 'Rejeter QC'), ('annoter', 'Annotation'), ('tamponner', 'Tampon'), ('signer', 'Signature'), ('commenter', 'Note'), ('telecharger', 'Téléchargement'), ('autre', 'Autre')], db_index=True, max_length=32),
        ),
    ]
