# Generated by Django 5.2.15 on 2026-07-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_acces', '0014_configuration_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationemail',
            name='default_from_email',
            field=models.CharField(blank=True, default='', help_text='Ex. GED <adresse@exemple.com>', max_length=255),
        ),
        migrations.AlterField(
            model_name='configurationemail',
            name='email_backend',
            field=models.CharField(blank=True, default='django.core.mail.backends.smtp.EmailBackend', help_text='Backend Django (SMTP ou console).', max_length=200),
        ),
        migrations.AlterField(
            model_name='configurationemail',
            name='email_host',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
