# Generated by Django 5.2.15 on 2026-07-18 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gestion_acces', '0015_configuration_email_empty_defaults'),
        ('gestion_documentaire', '0015_documentcomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalactivite',
            name='action',
            field=models.CharField(choices=[('connexion', 'Connexion'), ('deconnexion', 'Déconnexion'), ('connexion_echouee', 'Connexion échouée'), ('creation', 'Création'), ('modification', 'Modification'), ('suppression', 'Suppression'), ('soumettre_qc', 'Soumettre QC'), ('valider_qc', 'Valider QC'), ('rejeter_qc', 'Rejeter QC'), ('annoter', 'Annotation'), ('tamponner', 'Tampon'), ('signer', 'Signature'), ('commenter', 'Note'), ('telecharger', 'Téléchargement'), ('envoyer_email', 'Envoi e-mail'), ('autre', 'Autre')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='journalactivite',
            name='categorie',
            field=models.CharField(choices=[('authentification', 'Authentification'), ('utilisateurs', 'Utilisateurs'), ('groupes', 'Groupes'), ('documents', 'Documents'), ('parametrage', 'Paramétrage'), ('liens', 'Liens de téléchargement'), ('entreprise', 'Entreprise'), ('configuration_email', 'Configuration e-mail'), ('journal', "Journal d'activité"), ('autre', 'Autre')], db_index=True, default='autre', max_length=32),
        ),
        migrations.CreateModel(
            name='ModeleEmailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=150)),
                ('sujet', models.CharField(max_length=255)),
                ('corps_texte', models.TextField()),
                ('corps_html', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modeles_email_modifies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "modèle d'e-mail de notification",
                'verbose_name_plural': "modèles d'e-mail de notification",
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ConfigurationResumePeriodique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('frequence', models.CharField(choices=[('daily', 'Quotidien'), ('weekly', 'Hebdomadaire')], default='daily', max_length=10)),
                ('heure_envoi', models.TimeField(default='08:00')),
                ('jour_semaine', models.PositiveSmallIntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], default=0, help_text="Jour d'envoi lorsque la fréquence est hebdomadaire.")),
                ('min_documents', models.PositiveIntegerField(default=1, help_text="Nombre minimum de documents en attente pour déclencher l'envoi.")),
                ('dernier_envoi', models.DateTimeField(blank=True, null=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('modele', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configurations_resume', to='gestion_acces.modeleemailnotification')),
            ],
            options={
                'verbose_name': 'configuration du résumé périodique',
                'verbose_name_plural': 'configurations du résumé périodique',
            },
        ),
        migrations.CreateModel(
            name='NotificationEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('soumission', 'Soumission au contrôle qualité'), ('resoumission', 'Resoumission après rejet'), ('validation', 'Validation du document'), ('rejet', 'Rejet du document'), ('resume_periodique', 'Résumé périodique des documents en attente')], db_index=True, max_length=32)),
                ('document_label', models.CharField(blank=True, default='', max_length=255)),
                ('template_code', models.CharField(blank=True, default='', max_length=50)),
                ('recipient_email', models.CharField(blank=True, default='', max_length=254)),
                ('sujet', models.CharField(blank=True, default='', max_length=255)),
                ('statut', models.CharField(choices=[('queued', 'En file'), ('sent', 'Envoyé'), ('failed', 'Échec'), ('skipped', 'Ignoré')], db_index=True, default='queued', max_length=10)),
                ('skip_reason', models.CharField(blank=True, default='', max_length=255)),
                ('error_message', models.TextField(blank=True, default='')),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_email', to='gestion_documentaire.documentlocalite')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_recues', to=settings.AUTH_USER_MODEL)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_declenchees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'journal de notification e-mail',
                'verbose_name_plural': 'journaux de notification e-mail',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PreferenceNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_soumission', models.BooleanField(default=True)),
                ('notif_resoumission', models.BooleanField(default=True)),
                ('notif_validation', models.BooleanField(default=True)),
                ('notif_rejet', models.BooleanField(default=True)),
                ('resume_periodique', models.BooleanField(default=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference_notification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'préférence de notification',
                'verbose_name_plural': 'préférences de notification',
            },
        ),
        migrations.CreateModel(
            name='RegleNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('soumission', 'Soumission au contrôle qualité'), ('resoumission', 'Resoumission après rejet'), ('validation', 'Validation du document'), ('rejet', 'Rejet du document'), ('resume_periodique', 'Résumé périodique des documents en attente')], max_length=32, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('recipient_target', models.CharField(choices=[('createur', 'Créateur du document'), ('controleurs', 'Contrôleurs éligibles (permissions + périmètre)'), ('groupes', 'Groupes personnalisés'), ('utilisateurs', 'Utilisateurs personnalisés')], default='createur', max_length=32)),
                ('exclude_actor', models.BooleanField(default=True, help_text="Ne pas notifier l'utilisateur qui déclenche l'action.")),
                ('respecter_preferences', models.BooleanField(default=True, help_text='Respecter les préférences de notification de chaque utilisateur.')),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('modele', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regles', to='gestion_acces.modeleemailnotification')),
                ('recipient_groups', models.ManyToManyField(blank=True, related_name='regles_notification', to='auth.group')),
                ('recipient_users', models.ManyToManyField(blank=True, related_name='regles_notification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'règle de notification',
                'verbose_name_plural': 'règles de notification',
                'ordering': ['event_type'],
            },
        ),
    ]
