# Generated by Django 5.2.15 on 2026-07-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_acces', '0016_alter_journalactivite_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationemaillog',
            name='event_type',
            field=models.CharField(choices=[('soumission', 'Soumission au contrôle qualité'), ('validation', 'Validation du document'), ('rejet', 'Rejet du document'), ('resoumission', 'Resoumission après rejet'), ('resume_periodique', 'Résumé périodique des documents en attente')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='reglenotification',
            name='event_type',
            field=models.CharField(choices=[('soumission', 'Soumission au contrôle qualité'), ('validation', 'Validation du document'), ('rejet', 'Rejet du document'), ('resoumission', 'Resoumission après rejet'), ('resume_periodique', 'Résumé périodique des documents en attente')], max_length=32, unique=True),
        ),
    ]
