# Generated by Django 5.2.15 on 2026-09-02 16:37

import config.file_validation
import django.core.validators
import django.db.models.deletion
import gestion_acces.models.guide_aide
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_acces', '0020_lien_telechargement_security'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideAide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_code', models.CharField(choices=[('general', 'Général (premiers pas)'), ('parametrage', 'Paramétrage'), ('gestion_documentaire', 'Gestion Documentaire'), ('recherche_avancee', 'Recherche Avancée'), ('controle_qualite', 'Contrôle qualité'), ('analytique', 'Analytique & Rapports'), ('gestion_acces', 'Gestion des accès')], max_length=50)),
                ('titre', models.CharField(max_length=180)),
                ('description', models.CharField(blank=True, default='', max_length=400)),
                ('youtube_url', models.URLField(blank=True, default='', max_length=500)),
                ('video', models.FileField(blank=True, max_length=1024, null=True, upload_to=gestion_acces.models.guide_aide.aide_video_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm']), config.file_validation.UploadedFileValidator(kind='video', label='vidéo')])),
                ('guide', models.TextField(blank=True, default='', help_text='Texte du guide. Une étape par ligne.')),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guides_aide_modifies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "guide d'aide",
                'verbose_name_plural': "guides d'aide",
                'ordering': ['ordre', 'titre', 'id'],
                'default_permissions': (),
            },
        ),
    ]
