# Generated by Django 5.2.15 on 2026-09-02 16:49

import config.file_validation
import django.core.validators
import django.db.models.deletion
import gestion_acces.models.guide_aide
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_acces', '0021_guide_aide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guideaide',
            name='video',
        ),
        migrations.CreateModel(
            name='GuideAideDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(max_length=1024, upload_to=gestion_acces.models.guide_aide.aide_document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'gif']), config.file_validation.UploadedFileValidator(kind='document', label='document')])),
                ('nom_original', models.CharField(blank=True, default='', max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='gestion_acces.guideaide')),
            ],
            options={
                'verbose_name': "document de guide d'aide",
                'verbose_name_plural': "documents de guide d'aide",
                'ordering': ['id'],
                'default_permissions': (),
            },
        ),
    ]
