# Generated by Django 5.2.15 on 2026-09-02 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_acces', '0022_guide_aide_documents'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guideaide',
            options={'ordering': ['ordre', 'titre', 'id'], 'verbose_name': "guide d'aide", 'verbose_name_plural': "guides d'aide"},
        ),
    ]
