# Generated by Django 5.2.15 on 2026-09-30 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_acces', '0031_staff_follows_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reglenotification',
            name='respecter_preferences',
        ),
        migrations.DeleteModel(
            name='PreferenceNotification',
        ),
    ]
