# Generated by Django 5.2.7 on 2026-06-22 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametrage', '0006_plangeographique_latitude_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentLocalite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='documents/localites/%Y/%m/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_crees', to=settings.AUTH_USER_MODEL)),
                ('localite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='parametrage.plangeographique')),
                ('reponse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_localite', to='parametrage.reponsedocument')),
                ('type_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents_localite', to='parametrage.typedocument')),
            ],
            options={
                'verbose_name': 'Document localité',
                'verbose_name_plural': 'Documents localité',
                'ordering': ['-date_creation'],
            },
        ),
    ]
