# Generated by Django 5.2.7 on 2026-06-24 11:17

import gestion_documentaire.services.document_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_documentaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentlocalite',
            name='fichier',
            field=models.FileField(upload_to=gestion_documentaire.services.document_storage.document_upload_path),
        ),
    ]
