# Generated by Django 5.2.7 on 2026-06-24 11:26

import gestion_documentaire.services.document_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_documentaire', '0002_document_upload_plan_geo_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentlocalite',
            name='fichier',
            field=models.FileField(max_length=1024, upload_to=gestion_documentaire.services.document_storage.document_upload_path),
        ),
    ]
