# Generated by Django 5.2.7 on 2026-07-15 09:45

import config.file_validation
import django.core.validators
import django.db.models.deletion
import gestion_documentaire.services.document_storage
import gestion_documentaire.services.lot_brouillon_storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_documentaire', '0011_document_version_annotations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentlocalite',
            name='fichier',
            field=models.FileField(max_length=1024, upload_to=gestion_documentaire.services.document_storage.document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'gif']), config.file_validation.UploadedFileValidator(kind='document', label='document')]),
        ),
        migrations.AlterField(
            model_name='itemlotbrouillonrattachement',
            name='fichier',
            field=models.FileField(max_length=1024, upload_to=gestion_documentaire.services.lot_brouillon_storage.lot_brouillon_item_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'gif']), config.file_validation.UploadedFileValidator(kind='document', label='document')]),
        ),
        migrations.AlterField(
            model_name='lotbrouillonrattachement',
            name='utilisateur',
            field=models.ForeignKey(help_text='Dernier utilisateur ayant modifié ce brouillon.', on_delete=django.db.models.deletion.CASCADE, related_name='lots_brouillon_rattachement', to=settings.AUTH_USER_MODEL),
        ),
    ]
