# Generated by Django 5.2.7 on 2026-07-15 09:53

import config.file_validation
import django.core.validators
import gestion_documentaire.services.document_version_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_documentaire', '0012_secure_file_upload_validators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentversion',
            name='fichier',
            field=models.FileField(max_length=1024, upload_to=gestion_documentaire.services.document_version_storage.document_version_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'gif']), config.file_validation.UploadedFileValidator(kind='document', label='document')]),
        ),
    ]
