# Generated by Django 5.2.7 on 2026-06-17 17:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typedocument',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='typedocument',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ChampsDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_champ', models.CharField(max_length=100)),
                ('type_champ', models.CharField(choices=[('texte', 'Texte'), ('nombre', 'Nombre'), ('date', 'Date'), ('choix', 'Choix multiple'), ('select', 'Liste déroulante'), ('fichier', 'Fichier')], max_length=50)),
                ('obligatoire', models.BooleanField(default=False)),
                ('ordre', models.IntegerField(default=1)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('type_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='champs', to='parametrage.typedocument')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='OptionChamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.CharField(max_length=255)),
                ('champ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='parametrage.champsdocument')),
            ],
        ),
        migrations.CreateModel(
            name='ReponseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('type_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='parametrage.typedocument')),
            ],
        ),
        migrations.CreateModel(
            name='ValeurChamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.TextField(blank=True)),
                ('champ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametrage.champsdocument')),
                ('reponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valeurs', to='parametrage.reponsedocument')),
            ],
        ),
        migrations.AddConstraint(
            model_name='champsdocument',
            constraint=models.UniqueConstraint(fields=('type_document', 'ordre'), name='unique_ordre_champ_document'),
        ),
    ]
