# Generated by Django 5.2.7 on 2026-06-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrage', '0006_plangeographique_latitude_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champsdocument',
            name='type_champ',
            field=models.CharField(choices=[('texte', 'Texte court'), ('texte_long', 'Texte long'), ('nombre', 'Nombre'), ('date', 'Date'), ('datetime', 'Date et heure'), ('choix', 'Choix multiple'), ('select', 'Liste déroulante')], max_length=50),
        ),
    ]
