# Generated by Django 5.2.15 on 2026-06-26 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parametrage', '0008_capture_zones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='champsdocument',
            options={'ordering': ['ordre'], 'verbose_name': 'champ document', 'verbose_name_plural': 'champs documents'},
        ),
        migrations.AlterModelOptions(
            name='optionchamp',
            options={'verbose_name': 'option de champ', 'verbose_name_plural': 'options de champ'},
        ),
        migrations.AlterModelOptions(
            name='plangeographique',
            options={'ordering': ['id'], 'verbose_name': 'plan de classement', 'verbose_name_plural': 'plans de classement'},
        ),
        migrations.AlterModelOptions(
            name='reponsedocument',
            options={'verbose_name': 'réponse document', 'verbose_name_plural': 'réponses document'},
        ),
        migrations.AlterModelOptions(
            name='typedocument',
            options={'verbose_name': 'type de document', 'verbose_name_plural': 'types de documents'},
        ),
        migrations.AlterModelOptions(
            name='valeurchamp',
            options={'verbose_name': 'valeur de champ', 'verbose_name_plural': 'valeurs de champ'},
        ),
    ]
