# Generated by Django 5.2.7 on 2026-07-15 09:45

import config.file_validation
import django.core.validators
import parametrage.capture_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrage', '0010_alter_champsdocument_type_champ_qr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typedocument',
            name='fichier_modele',
            field=models.FileField(blank=True, help_text="PDF ou image servant de modèle pour l'encadrement des champs.", null=True, upload_to=parametrage.capture_storage.capture_modele_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'gif']), config.file_validation.UploadedFileValidator(kind='document', label='modèle')]),
        ),
    ]
